---
abstract: 'An ASCII game for fun '
author:
  - 'tadegenban <tadegenban@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.133380'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-FrogJump
requires:
  Color::ANSI::Util: 0
  File::HomeDir: 0
  File::Spec::Functions: 0
  List::Util: 0
  Moo: 0
  Storable: 0
  Term::ANSIColor: 0
  Term::ReadKey: 0
  Text::Wrap: 0
  Time::HiRes: 0
  constant: 0
  if: 0
  perl: 5.012
  strict: 0
  warnings: 0
version: 0.03
